name: Python Tests

on:
  push:
    branches: [ main ]  # Change to your main branch name if different
  pull_request:
    branches: [ main ]  # Change to your main branch name if different

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Test against multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Use pyproject.toml if not using requirements.txt
        # pip install .

    - name: Run tests
      run: |
        python -m unittest discover -s tests
